//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAE.CartifService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/CartifService.asmx/", ConfigurationName="CartifService.CartifServiceSoap")]
    public interface CartifServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://localhost/CartifService.asmx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CartifService.asmx/LoginPostgres", ReplyAction="*")]
        LAE.CartifService.LoginPostgresResponse LoginPostgres(LAE.CartifService.LoginPostgresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CartifService.asmx/LoginPostgres", ReplyAction="*")]
        System.Threading.Tasks.Task<LAE.CartifService.LoginPostgresResponse> LoginPostgresAsync(LAE.CartifService.LoginPostgresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://localhost/CartifService.asmx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CartifService.asmx/LoginZimbra", ReplyAction="*")]
        LAE.CartifService.LoginZimbraResponse LoginZimbra(LAE.CartifService.LoginZimbraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CartifService.asmx/LoginZimbra", ReplyAction="*")]
        System.Threading.Tasks.Task<LAE.CartifService.LoginZimbraResponse> LoginZimbraAsync(LAE.CartifService.LoginZimbraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://localhost/CartifService.asmx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CartifService.asmx/LoginLDAPZimbra", ReplyAction="*")]
        LAE.CartifService.LoginLDAPZimbraResponse LoginLDAPZimbra(LAE.CartifService.LoginLDAPZimbraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CartifService.asmx/LoginLDAPZimbra", ReplyAction="*")]
        System.Threading.Tasks.Task<LAE.CartifService.LoginLDAPZimbraResponse> LoginLDAPZimbraAsync(LAE.CartifService.LoginLDAPZimbraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginPostgresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginPostgres", Namespace="http://localhost/CartifService.asmx/", Order=0)]
        public LAE.CartifService.LoginPostgresRequestBody Body;
        
        public LoginPostgresRequest() {
        }
        
        public LoginPostgresRequest(LAE.CartifService.LoginPostgresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CartifService.asmx/")]
    public partial class LoginPostgresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public LoginPostgresRequestBody() {
        }
        
        public LoginPostgresRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginPostgresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginPostgresResponse", Namespace="http://localhost/CartifService.asmx/", Order=0)]
        public LAE.CartifService.LoginPostgresResponseBody Body;
        
        public LoginPostgresResponse() {
        }
        
        public LoginPostgresResponse(LAE.CartifService.LoginPostgresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CartifService.asmx/")]
    public partial class LoginPostgresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginPostgresResult;
        
        public LoginPostgresResponseBody() {
        }
        
        public LoginPostgresResponseBody(bool LoginPostgresResult) {
            this.LoginPostgresResult = LoginPostgresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginZimbraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginZimbra", Namespace="http://localhost/CartifService.asmx/", Order=0)]
        public LAE.CartifService.LoginZimbraRequestBody Body;
        
        public LoginZimbraRequest() {
        }
        
        public LoginZimbraRequest(LAE.CartifService.LoginZimbraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CartifService.asmx/")]
    public partial class LoginZimbraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public LoginZimbraRequestBody() {
        }
        
        public LoginZimbraRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginZimbraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginZimbraResponse", Namespace="http://localhost/CartifService.asmx/", Order=0)]
        public LAE.CartifService.LoginZimbraResponseBody Body;
        
        public LoginZimbraResponse() {
        }
        
        public LoginZimbraResponse(LAE.CartifService.LoginZimbraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CartifService.asmx/")]
    public partial class LoginZimbraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginZimbraResult;
        
        public LoginZimbraResponseBody() {
        }
        
        public LoginZimbraResponseBody(bool LoginZimbraResult) {
            this.LoginZimbraResult = LoginZimbraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginLDAPZimbraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginLDAPZimbra", Namespace="http://localhost/CartifService.asmx/", Order=0)]
        public LAE.CartifService.LoginLDAPZimbraRequestBody Body;
        
        public LoginLDAPZimbraRequest() {
        }
        
        public LoginLDAPZimbraRequest(LAE.CartifService.LoginLDAPZimbraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CartifService.asmx/")]
    public partial class LoginLDAPZimbraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public LoginLDAPZimbraRequestBody() {
        }
        
        public LoginLDAPZimbraRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginLDAPZimbraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginLDAPZimbraResponse", Namespace="http://localhost/CartifService.asmx/", Order=0)]
        public LAE.CartifService.LoginLDAPZimbraResponseBody Body;
        
        public LoginLDAPZimbraResponse() {
        }
        
        public LoginLDAPZimbraResponse(LAE.CartifService.LoginLDAPZimbraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CartifService.asmx/")]
    public partial class LoginLDAPZimbraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginLDAPZimbraResult;
        
        public LoginLDAPZimbraResponseBody() {
        }
        
        public LoginLDAPZimbraResponseBody(bool LoginLDAPZimbraResult) {
            this.LoginLDAPZimbraResult = LoginLDAPZimbraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CartifServiceSoapChannel : LAE.CartifService.CartifServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartifServiceSoapClient : System.ServiceModel.ClientBase<LAE.CartifService.CartifServiceSoap>, LAE.CartifService.CartifServiceSoap {
        
        public CartifServiceSoapClient() {
        }
        
        public CartifServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartifServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartifServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartifServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LAE.CartifService.LoginPostgresResponse LAE.CartifService.CartifServiceSoap.LoginPostgres(LAE.CartifService.LoginPostgresRequest request) {
            return base.Channel.LoginPostgres(request);
        }
        
        public bool LoginPostgres(string usuario, string contraseña) {
            LAE.CartifService.LoginPostgresRequest inValue = new LAE.CartifService.LoginPostgresRequest();
            inValue.Body = new LAE.CartifService.LoginPostgresRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            LAE.CartifService.LoginPostgresResponse retVal = ((LAE.CartifService.CartifServiceSoap)(this)).LoginPostgres(inValue);
            return retVal.Body.LoginPostgresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LAE.CartifService.LoginPostgresResponse> LAE.CartifService.CartifServiceSoap.LoginPostgresAsync(LAE.CartifService.LoginPostgresRequest request) {
            return base.Channel.LoginPostgresAsync(request);
        }
        
        public System.Threading.Tasks.Task<LAE.CartifService.LoginPostgresResponse> LoginPostgresAsync(string usuario, string contraseña) {
            LAE.CartifService.LoginPostgresRequest inValue = new LAE.CartifService.LoginPostgresRequest();
            inValue.Body = new LAE.CartifService.LoginPostgresRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((LAE.CartifService.CartifServiceSoap)(this)).LoginPostgresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LAE.CartifService.LoginZimbraResponse LAE.CartifService.CartifServiceSoap.LoginZimbra(LAE.CartifService.LoginZimbraRequest request) {
            return base.Channel.LoginZimbra(request);
        }
        
        public bool LoginZimbra(string usuario, string contraseña) {
            LAE.CartifService.LoginZimbraRequest inValue = new LAE.CartifService.LoginZimbraRequest();
            inValue.Body = new LAE.CartifService.LoginZimbraRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            LAE.CartifService.LoginZimbraResponse retVal = ((LAE.CartifService.CartifServiceSoap)(this)).LoginZimbra(inValue);
            return retVal.Body.LoginZimbraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LAE.CartifService.LoginZimbraResponse> LAE.CartifService.CartifServiceSoap.LoginZimbraAsync(LAE.CartifService.LoginZimbraRequest request) {
            return base.Channel.LoginZimbraAsync(request);
        }
        
        public System.Threading.Tasks.Task<LAE.CartifService.LoginZimbraResponse> LoginZimbraAsync(string usuario, string contraseña) {
            LAE.CartifService.LoginZimbraRequest inValue = new LAE.CartifService.LoginZimbraRequest();
            inValue.Body = new LAE.CartifService.LoginZimbraRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((LAE.CartifService.CartifServiceSoap)(this)).LoginZimbraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LAE.CartifService.LoginLDAPZimbraResponse LAE.CartifService.CartifServiceSoap.LoginLDAPZimbra(LAE.CartifService.LoginLDAPZimbraRequest request) {
            return base.Channel.LoginLDAPZimbra(request);
        }
        
        public bool LoginLDAPZimbra(string usuario, string contraseña) {
            LAE.CartifService.LoginLDAPZimbraRequest inValue = new LAE.CartifService.LoginLDAPZimbraRequest();
            inValue.Body = new LAE.CartifService.LoginLDAPZimbraRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            LAE.CartifService.LoginLDAPZimbraResponse retVal = ((LAE.CartifService.CartifServiceSoap)(this)).LoginLDAPZimbra(inValue);
            return retVal.Body.LoginLDAPZimbraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LAE.CartifService.LoginLDAPZimbraResponse> LAE.CartifService.CartifServiceSoap.LoginLDAPZimbraAsync(LAE.CartifService.LoginLDAPZimbraRequest request) {
            return base.Channel.LoginLDAPZimbraAsync(request);
        }
        
        public System.Threading.Tasks.Task<LAE.CartifService.LoginLDAPZimbraResponse> LoginLDAPZimbraAsync(string usuario, string contraseña) {
            LAE.CartifService.LoginLDAPZimbraRequest inValue = new LAE.CartifService.LoginLDAPZimbraRequest();
            inValue.Body = new LAE.CartifService.LoginLDAPZimbraRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((LAE.CartifService.CartifServiceSoap)(this)).LoginLDAPZimbraAsync(inValue);
        }
    }
}
